# This file was generated by GoReleaser. DO NOT EDIT.
cask "wb" do
  version "0.134.1"

  on_macos do
    on_arm do
      sha256 "455ac80be212eb90ca34b1ce78831af04e9ec34b84edd82bebd3ba3fefebe0c4"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "efc7249d79745c1c0e939b3ac69e207055f2bc4ad2e1527f5b4824c272c689af"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2ed5f728a49bb6e84a701342ede887aa8aa1e15364c931a1508615f4f31bebd1"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fec1cbd92c75f02790a584ac633bb55df8d9cba4fe2bae100a3ffc4c5d6f1889"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wb"
  desc "wb — the Sneat workbench CLI: fleet-wide GitHub repo sync and config-driven recipes."
  homepage "https://sneat.work/bench"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wb"

  # No zap stanza required
end
