# This file was generated by GoReleaser. DO NOT EDIT.
cask "wb" do
  version "0.37.1"

  on_macos do
    on_intel do
      sha256 "44e4b0a0ca21e83e465907b02282813c00ec18e729cc03bd4fb0ebbbed4e247f"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "806d52a8f30b555b76112bb4c6dd8e9bff1b2002fabf7645db5b11ed64c88a56"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cd93199d35f7ca46ad4c356d6ef36506a33f976f6d2b712623b568c35a9a5531"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "277d38dd87aa192bd5582643412bb13d71a5e67c5dab659048abbcb68f558eb0"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "wb"
  desc "wb — the Sneat workbench CLI: fleet-wide GitHub repo sync and config-driven recipes."
  homepage "https://sneat.dev/workbench/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wb"

  postflight do
    if system_command "/usr/bin/xattr", args: ["-h"], print_stderr: false
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wb"]
    end
  end

  # No zap stanza required

end
