# This file was generated by GoReleaser. DO NOT EDIT.
cask "wb" do
  version "0.136.0"

  on_macos do
    on_arm do
      sha256 "c95a5d13fde381143a53bc31c9606b4ec1f864019990749ab8d3784f1aeff1bb"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "16fdbf27156b25e3196d689e47daa998be8bc3854baf6aec095cd20ff6801bc3"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5fdcab6f29400d9decad04f830ec0d685b8651cd1168ca99779bac7c63303b9e"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "afae4d5869d918407f5629a0a59ea0e2346a3a9aed25ddc3d3322d78a88d7ee5"
      url "https://github.com/sneat-dev/wb/releases/download/v#{version}/wb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wb"
  desc "wb — the Sneat workbench CLI: fleet-wide GitHub repo sync and config-driven recipes."
  homepage "https://sneat.work/bench"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wb"

  # No zap stanza required
end
